### ISSUE TITLE
SSL, hcloud-cloud-controller-manager pod dies

### ISSUE THREAD

**Issue by alrf** [hetznercloud/hcloud-cloud-controller-manager#229]
I'm using bitnami nginx helm chart: https://github.com/bitnami/charts/tree/master/bitnami/nginx with these settings in yaml:

```
containerPorts:
  http: 8080
  https: 8080

....

service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  targetPort:
    http: http
    https: http
  loadBalancerIP: ""
  annotations:
    load-balancer.hetzner.cloud/name: "nginx-es-lb"
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/hostname: my.domain.com
    load-balancer.hetzner.cloud/protocol: https
    load-balancer.hetzner.cloud/http-certificates: certificate-1
```

In this case Hetzner LB can't be issued (`kubectl get svc` shows it in "pending" state) and `hcloud-cloud-controller-manager` pod dies with errors:
```
I0804 10:18:11.179811       1 event.go:278] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"my-release-nginx", UID:"a7f85d51-3de8-416c-b97e-e6a2a40e03ad", APIVersion:"v1", ResourceVersion:"38695", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
I0804 10:18:11.205854       1 load_balancers.go:81] "ensure Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" service="my-release-nginx" nodes=[k8s-es-2-58bd574dbf-7rpcm k8s-es-2-58bd574dbf-cf2t9 k8s-es-2-58bd574dbf-rdpvx]
I0804 10:18:14.599161       1 load_balancer.go:390] "add target" op="hcops/LoadBalancerOps.ReconcileHCLBTargets" service="my-release-nginx" targetName="k8s-es-2-58bd574dbf-7rpcm"
I0804 10:18:15.612904       1 load_balancer.go:390] "add target" op="hcops/LoadBalancerOps.ReconcileHCLBTargets" service="my-release-nginx" targetName="k8s-es-2-58bd574dbf-cf2t9"
I0804 10:18:16.890309       1 load_balancer.go:390] "add target" op="hcops/LoadBalancerOps.ReconcileHCLBTargets" service="my-release-nginx" targetName="k8s-es-2-58bd574dbf-rdpvx"
I0804 10:18:18.116419       1 load_balancer.go:450] "add service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=80 loadBalancerID=388582
E0804 10:18:18.116775       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 206 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x192fb40, 0x2912e60)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:48 +0x89
panic(0x192fb40, 0x2912e60)
    /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/hetznercloud/hcloud-go/hcloud.loadBalancerAddServiceOptsToSchema(0xc00057a0ab, 0x5, 0xc0005c38a8, 0xc0005c38b0, 0x0, 0xc00089ed00, 0xc00089ed40, 0x0, 0x0, 0x0, ...)
    /go/pkg/mod/github.com/hetznercloud/hcloud-go@v1.22.0/hcloud/schema.go:808 +0x1dc
github.com/hetznercloud/hcloud-go/hcloud.(*LoadBalancerClient).AddService(0xc00022c288, 0x1dd4aa0, 0xc00009c018, 0xc00093a800, 0xc00057a0ab, 0x5, 0xc0005c38a8, 0xc0005c38b0, 0x0, 0xc00089ed00, ...)
    /go/pkg/mod/github.com/hetznercloud/hcloud-go@v1.22.0/hcloud/load_balancer.go:647 +0x6a
github.com/hetznercloud/hcloud-cloud-controller-manager/internal/hcops.(*LoadBalancerOps).ReconcileHCLBServices(0xc000281a80, 0x1dd4aa0, 0xc00009c018, 0xc00093a800, 0xc00019a240, 0xc00078b4a0, 0x3, 0x4)
    /maschine-controller/src/internal/hcops/load_balancer.go:457 +0x100a
github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*loadBalancers).EnsureLoadBalancer(0xc00051ba70, 0x1dd4aa0, 0xc00009c018, 0x1b88653, 0xa, 0xc00019a240, 0xc00078b4a0, 0x3, 0x4, 0xc00019ab40, ...)
    /maschine-controller/src/hcloud/load_balancers.go:110 +0x5e2
k8s.io/kubernetes/pkg/controller/service.(*Controller).ensureLoadBalancer(0xc00095c460, 0xc00019a240, 0x0, 0x0, 0x6)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:389 +0xde
k8s.io/kubernetes/pkg/controller/service.(*Controller).syncLoadBalancerIfNeeded(0xc00095c460, 0xc00019a240, 0xc000724020, 0x18, 0xc0006cdcb0, 0x1526313, 0x1df0360)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:344 +0x889
k8s.io/kubernetes/pkg/controller/service.(*Controller).processServiceCreateOrUpdate(0xc00095c460, 0xc00019a240, 0xc000724020, 0x18, 0x0, 0x0)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:280 +0xd9
k8s.io/kubernetes/pkg/controller/service.(*Controller).syncService(0xc00095c460, 0xc000724020, 0x18, 0x0, 0x0)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:759 +0x31a
k8s.io/kubernetes/pkg/controller/service.(*Controller).processNextWorkItem(0xc00095c460, 0x203000)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:238 +0xf5
k8s.io/kubernetes/pkg/controller/service.(*Controller).worker(0xc00095c460)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:227 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008f8d10)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008f8d10, 0x1d8e4c0, 0xc000aa6ab0, 0xc000713c01, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008f8d10, 0x3b9aca00, 0x0, 0x100000000000001, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0008f8d10, 0x3b9aca00, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/controller/service.(*Controller).Run
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:216 +0x20e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17554bc]

goroutine 206 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x192fb40, 0x2912e60)
    /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/hetznercloud/hcloud-go/hcloud.loadBalancerAddServiceOptsToSchema(0xc00057a0ab, 0x5, 0xc0005c38a8, 0xc0005c38b0, 0x0, 0xc00089ed00, 0xc00089ed40, 0x0, 0x0, 0x0, ...)
    /go/pkg/mod/github.com/hetznercloud/hcloud-go@v1.22.0/hcloud/schema.go:808 +0x1dc
github.com/hetznercloud/hcloud-go/hcloud.(*LoadBalancerClient).AddService(0xc00022c288, 0x1dd4aa0, 0xc00009c018, 0xc00093a800, 0xc00057a0ab, 0x5, 0xc0005c38a8, 0xc0005c38b0, 0x0, 0xc00089ed00, ...)
    /go/pkg/mod/github.com/hetznercloud/hcloud-go@v1.22.0/hcloud/load_balancer.go:647 +0x6a
github.com/hetznercloud/hcloud-cloud-controller-manager/internal/hcops.(*LoadBalancerOps).ReconcileHCLBServices(0xc000281a80, 0x1dd4aa0, 0xc00009c018, 0xc00093a800, 0xc00019a240, 0xc00078b4a0, 0x3, 0x4)
    /maschine-controller/src/internal/hcops/load_balancer.go:457 +0x100a
github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*loadBalancers).EnsureLoadBalancer(0xc00051ba70, 0x1dd4aa0, 0xc00009c018, 0x1b88653, 0xa, 0xc00019a240, 0xc00078b4a0, 0x3, 0x4, 0xc00019ab40, ...)
    /maschine-controller/src/hcloud/load_balancers.go:110 +0x5e2
k8s.io/kubernetes/pkg/controller/service.(*Controller).ensureLoadBalancer(0xc00095c460, 0xc00019a240, 0x0, 0x0, 0x6)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:389 +0xde
k8s.io/kubernetes/pkg/controller/service.(*Controller).syncLoadBalancerIfNeeded(0xc00095c460, 0xc00019a240, 0xc000724020, 0x18, 0xc0006cdcb0, 0x1526313, 0x1df0360)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:344 +0x889
k8s.io/kubernetes/pkg/controller/service.(*Controller).processServiceCreateOrUpdate(0xc00095c460, 0xc00019a240, 0xc000724020, 0x18, 0x0, 0x0)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:280 +0xd9
k8s.io/kubernetes/pkg/controller/service.(*Controller).syncService(0xc00095c460, 0xc000724020, 0x18, 0x0, 0x0)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:759 +0x31a
k8s.io/kubernetes/pkg/controller/service.(*Controller).processNextWorkItem(0xc00095c460, 0x203000)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:238 +0xf5
k8s.io/kubernetes/pkg/controller/service.(*Controller).worker(0xc00095c460)
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:227 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008f8d10)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008f8d10, 0x1d8e4c0, 0xc000aa6ab0, 0xc000713c01, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008f8d10, 0x3b9aca00, 0x0, 0x100000000000001, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0008f8d10, 0x3b9aca00, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/controller/service.(*Controller).Run
    /go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:216 +0x20e
```

**Comment by alrf** [comment]
Wrong annotations, "IDs or Names":
```
// LBSvcHTTPCertificates a comma separated list of IDs or Names of
// Certificates assigned to the service.
//
// HTTPS only.
LBSvcHTTPCertificates Name = "load-balancer.hetzner.cloud/http-certificates"
```
https://pkg.go.dev/github.com/hetznercloud/hcloud-cloud-controller-manager/internal/annotation

the same here:
https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/b54847b9163a3fc39dd902ab2f5f0494003b7230/internal/annotation/load_balancer.go#L115-L119

In fact, it works only with IDs and fails with name..

Workable example:
```
annotations:
    load-balancer.hetzner.cloud/name: "nginx-es-lb"
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/hostname: my.domain.com
    load-balancer.hetzner.cloud/protocol: https
    load-balancer.hetzner.cloud/certificate-type: "uploaded"
    load-balancer.hetzner.cloud/http-certificates: "482204" ### cert ID
```

**Comment by LKaemmerling** [comment]
Hey @alrf,

which Cloud Controler Manager version do you use? IIRC we fixed this with one of the last two releases.
