### ISSUE TITLE
Nil pointer dereference when using network version with multiple subnets

### ISSUE THREAD

**Issue by bpasson** [hetznercloud/hcloud-cloud-controller-manager#42]
A nil pointer dereference keeps occuring when I use the network version of the conroller. Not sure if this is a configuration issue or an other issue. Keys and network id are configured and ok as it worked when there were no subnets defined but broke once I defined subnets.

The cloud controller is deployed in Kubernetes v1.18.2.

```
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
ERROR: logging before flag.Parse: W0518 06:55:01.586721       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: W0518 06:55:02.606795       1 controllermanager.go:108] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
ERROR: logging before flag.Parse: W0518 06:55:02.607266       1 authentication.go:55] Authentication is disabled
ERROR: logging before flag.Parse: I0518 06:55:02.607434       1 insecure_serving.go:49] Serving insecurely on [::]:10253
ERROR: logging before flag.Parse: I0518 06:55:02.608997       1 node_controller.go:89] Sending events to api server.
ERROR: logging before flag.Parse: I0518 06:55:02.610693       1 pvlcontroller.go:107] Starting PersistentVolumeLabelController
ERROR: logging before flag.Parse: E0518 06:55:02.611437       1 controllermanager.go:240] Failed to start service controller: the cloud provider does not support external load balancers
ERROR: logging before flag.Parse: I0518 06:55:02.616541       1 controller_utils.go:1025] Waiting for caches to sync for persistent volume label controller
ERROR: logging before flag.Parse: I0518 06:55:02.716799       1 controller_utils.go:1032] Caches are synced for persistent volume label controller
ERROR: logging before flag.Parse: I0518 06:55:04.228080       1 route_controller.go:102] Starting route controller
ERROR: logging before flag.Parse: I0518 06:55:04.228114       1 controller_utils.go:1025] Waiting for caches to sync for route controller
ERROR: logging before flag.Parse: I0518 06:55:04.328390       1 controller_utils.go:1032] Caches are synced for route controller
ERROR: logging before flag.Parse: E0518 06:55:04.329253       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:72
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:65
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/maschine-controller/src/hcloud/routes.go:31
/maschine-controller/src/hcloud/routes.go:59
/go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:128
/go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:119
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:133
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:134
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:98
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1088426]

goroutine 107 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x161ed40, 0x29730f0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*routes).reloadNetwork(0xc0004c0b60, 0x1ae52e0, 0xc00009c018, 0x203000, 0xc0004c0680)
        /maschine-controller/src/hcloud/routes.go:31 +0x36
github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*routes).ListRoutes(0xc0004c0b60, 0x1ae52e0, 0xc00009c018, 0x184992e, 0xa, 0xc0005f4610, 0x44bdb6, 0xc000420dc0, 0x7, 0x8)
        /maschine-controller/src/hcloud/routes.go:59 +0x5a
k8s.io/kubernetes/pkg/controller/route.(*RouteController).reconcileNodeRoutes(0xc00025c1c0, 0x44bb4b, 0xc00036c6e8)
        /go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:128 +0x73
k8s.io/kubernetes/pkg/controller/route.(*RouteController).Run.func1()
        /go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:119 +0x2e
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004f18d0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004f18d0, 0x2540be400, 0x0, 0x6d59744647610a00, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(0xc0004f18d0, 0x2540be400, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:98 +0x4d
created by k8s.io/kubernetes/pkg/controller/route.(*RouteController).Run
        /go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:118 +0x1f2
```

**Comment by fhofherr** [comment]
Hi @bpasson,

thank you for reporting the issue. It should be fixed in version 1.5.2.
