### ISSUE TITLE
Crash when LBs are deactivated

### ISSUE THREAD

**Issue by drallgood** [hetznercloud/hcloud-cloud-controller-manager#77]
I set the new env option to disable the LB handling.
However, that causes a crash in the module:
```E0821 22:54:29.722862       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 197 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18c91c0, 0x2ba3980)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18c91c0, 0x2ba3980)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*loadBalancers).EnsureLoadBalancer(0x0, 0x1e109a0, 0xc000046030, 0x1b3466c, 0xa, 0xc0008d6840, 0xc000838000, 0x6, 0x8, 0x1b2eb43, ...)
	/maschine-controller/src/hcloud/load_balancers.go:84 +0x28e
k8s.io/kubernetes/pkg/controller/service.(*Controller).ensureLoadBalancer(0xc00066cb60, 0xc0008d6840, 0x0, 0x0, 0x6)
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:389 +0xde
k8s.io/kubernetes/pkg/controller/service.(*Controller).syncLoadBalancerIfNeeded(0xc00066cb60, 0xc0008d6840, 0xc0004034c0, 0x1b, 0xc000111580, 0xc000969cb0, 0x14b7743)
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:344 +0x879
k8s.io/kubernetes/pkg/controller/service.(*Controller).processServiceCreateOrUpdate(0xc00066cb60, 0xc0008d6840, 0xc0004034c0, 0x1b, 0x0, 0x0)
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:280 +0xdf
k8s.io/kubernetes/pkg/controller/service.(*Controller).syncService(0xc00066cb60, 0xc0004034c0, 0x1b, 0x0, 0x0)
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:759 +0x30a
k8s.io/kubernetes/pkg/controller/service.(*Controller).processNextWorkItem(0xc00066cb60, 0x203000)
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:238 +0xf0
k8s.io/kubernetes/pkg/controller/service.(*Controller).worker(0xc00066cb60)
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:227 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00040f4f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00040f4f0, 0x1dc8960, 0xc000327f80, 0xc0003adb01, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00040f4f0, 0x3b9aca00, 0x0, 0x1bf9e01, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00040f4f0, 0x3b9aca00, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/controller/service.(*Controller).Run
	/go/pkg/mod/k8s.io/kubernetes@v1.18.3/pkg/controller/service/controller.go:216 +0x205
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x170053e]```

**Comment by LKaemmerling** [comment]
@drallgood are you sure you set the option to false? 
https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/hcloud/cloud.go#L107

**Comment by drallgood** [comment]
Yes. When I set it to true, it kinda works (complains about missing labels but is fine otherwise)
